---
title: "Temakveld og Medlemsmøter"
format: 
  html:
    toc: true
    toc-location: left
editor: source
---


<br>

<p style="font-family: times, serif; font-size:18pt; font-style:italic">
**Temakveld og Medlemsmøter i den større Oslo-regionen**
</p>

### 🎉 22.05.2025 
</b>

"_Statistical modelling using gradient boosting algorithms: applications across diverse fields_" 
with 
<span style="color:red">Riccardo De Bin</span>

<u>Program</u>:

17.00 - 17.20: Pizza, sushi and beverages

17.20 - 17.30: Annual meeting

17.30 - 18.30: Presentation by Riccardo De Bin

**Place**: Norwegian Computing Center (NR), ([Alfa-Omega room, Gaustadalléen 23A, 0373 Oslo](https://www.google.com/maps/place/data=!4m2!3m1!1s0x46416de8aff21e49:0x79354ac1e7ca82b3?sa=X&ved=1t:8290&ictx=111)) 

**Speaker**: Riccardo De Bin, UiO

**Title**: <span style="color:red">
Statistical modelling using gradient boosting algorithms: applications across diverse fields
</span>
 
  
**Abstract**:

In this talk we will see how the gradient boosting approach can be used to fit statistical models in various contexts: in the analysis of omics data through First Hitting Time models; in the prediction of the remaining useful life of lithium-ion batteries; in the assessment of airport runway conditions for safe landings; and in the analysis of the properties of transition metal complexes for catalysis. 
Statistical issues addressed in this talk include the extensions of classical survival models to the high dimensional frameworks, where the number of variables is (much) larger than the number of observations; the handling of informative censoring in survival models; and the exploration of graph structures. </b>

<br>

### 🎉 xx.xx.2025 i Ås

...

<br>

### 🎉 xx.xx.2024

...


<br>

### 🎉 28.11.2023 

</b>

"_Modellering av en forskers publiserings- og siteringsrate_" 
med 
<span style="color:red">Magne Aldrin</span>

<u>Program</u>:

17.00 - 17.30: Pizza, sushi og drikke

17.30 - 18.30: Presentasjon ved Magne Aldrin

**Hvor**: Universitetet i Oslo, (Abels utsikt, 12. etasje, Niels Henrik Abels hus - Universitetet I Oslo, Moltke Moes vei 35) og Zoom

**Foredragsholder**: Magne Aldrin, Forskningsleder, NR

**Tittel**: <span style="color:red">
Modellering av en forskers publiserings- og siteringsrate
</span>
 
  
**Abstrakt**:

Blir forskere mer produktive når de blir eldre? 
Er forskeren som tok doktorgrad tidlig i sin karriere mer produktiv enn de som gjorde det seinere? 
Vi, dvs. min kollega Olav Nikolai Breivik og jeg, undersøker dette ved å modellere her hvordan publiseringsraten (antall artikler o.l. per år) og siteringsraten til en gitt forsker forskjellige over tid som en funksjon av forklaringsvariabler knyttet til forskeren. 
Av særskilt interesse er om en forsker som får tildelt et såkalt FRIPRO-prosjektet fra Norges forskningsråd (NFR) får økt sin vitenskapelige produksjon sammenlignet med en sammenlignbar forsker som ikke får et slikt prosjekt. 
For å undersøke dette har vi et brukt et datasett med 2500 forskere som til sammen sendte inn 5000 søknader om FRIPRO-prosjekter i perioden 2004-2012, med informasjon om deres publiseringshistorie før og etter søknaden, til sammen 70000 publikasjoner. 
Vi modellerer årlig publiserings- og siteringsrate i etterkant av søknaden som funksjon av blant annet om forskeren fikk innvilget søknaden eller ikke, tid etter søknaden, alder, kjønn og tidligere publikasjonshistorie. 
Vi bruker generaliserte additive modeller (GAM). 
Modellene er programmert i programmeringssystemet TMB, som gir mulighet for fleksibel modellering og rask optimering basert på automatisk avledning. 
Dette systemet finnes nå i en rein R-versjon, RTMB, og jeg vil gi en kort innføring til det som en liten smakebit til TMB-kurset som Olav Nikolai Breivik vil holde i forkant av neste års norske statistikkmøte i Tønsberg. 
Arbeidet som presenteres har blitt utført på oppdrag fra Norges forskningsråd. </b>

<br>